### ISSUE TITLE
sshx in CI/CD of public projects can have public logs

### ISSUE THREAD

**Issue by NikolayS** [ekzhang/sshx#23]
Great project!

But speaking of CI/CD, consider scenario:

- to debug, someone puts sshx to CI/CD of their open-source project
- the URL is printed in the CI/CD output and anyone can read it
- anyone can connect
- `printenv` shows all environment variables, including secrets (if any, of course)

I'd add at least a warning about this in the README.

**Comment by NikolayS** [comment]
BTW, in this context:

- if machine is destroyed, does the browser link keep working?
- if yes, can it be deleted manually or automatically deleted later?

**Comment by ekzhang** [comment]
Yes this is true, good catch. You need to disable public access to the logs of CI builds if you want to use sshx in a context like that.

In practice the risk is quite low because it's an ephemeral app run, but it doesn't hurt to be safe with the usage recommendation.

sshx disconnects if the machine disconnects. The session is garbage collected after a few minutes if the same client does not reconnect.
