### ISSUE TITLE
Create github releases including releasing binaries

### ISSUE THREAD

**Issue by jankatins** [ekzhang/sshx#73]
I use github releases to get notified about new releases of projects and also have some process to automatically download new releases for my arch&os. It would be nice if sshx could make such releases available (e.g. via automatic pipelines as already mentioned in https://github.com/ekzhang/sshx/issues/35 or using others projects release pipeline e.g. https://github.com/mitsuhiko/rye/blob/main/.github/workflows/release.yml)

**Comment by dch** [comment]
I'm porting this to FreeBSD and need a git tag to build off. Would be great if we can have tags in the source code.

**Comment by ekzhang** [comment]
We have tags for the latest release. I'm closing this now.

Unfortunately I'm not going to build release binaries into CI because I've found that process to be somewhat brittle in the past. If it fails for any reason (network, GitHub down, API issues, cosmic ray, etc.) then you need to find a way to rerun the CI step. Sorry!
